name: Linting and Formatting Checks
on: pull_request

jobs:
  black:
    name: runner / black formatter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv tool run black . --check --diff

  ruff:
    name: runner / ruff linter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6
      - run: uv tool run ruff check
